import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <Toaster
        toastOptions={{
          className: "",
          style: {
            border: "5px solid #713200",
            padding: "16px",
            color: "#713200",
            backgroundColor: "white",
            fontSize:"1.2rem",
          },
        }}
      />{" "}
      </body>
     
    </html>
  );
}
